var annotated_dup =
[
    [ "AltimeterScript", "class_altimeter_script.html", "class_altimeter_script" ],
    [ "ButtonTransitionScript", "class_button_transition_script.html", "class_button_transition_script" ],
    [ "ChallengeMode", "class_challenge_mode.html", "class_challenge_mode" ],
    [ "CollectibleBehavior", "class_collectible_behavior.html", "class_collectible_behavior" ],
    [ "FallingBehaviorManager", "class_falling_behavior_manager.html", "class_falling_behavior_manager" ],
    [ "FreeFallBehavior", "class_free_fall_behavior.html", "class_free_fall_behavior" ],
    [ "HelicopterFlight", "class_helicopter_flight.html", "class_helicopter_flight" ],
    [ "IFallBehavior", "interface_i_fall_behavior.html", "interface_i_fall_behavior" ],
    [ "ImmersiveMode", "class_immersive_mode.html", "class_immersive_mode" ],
    [ "IncomingProjectileUI", "class_incoming_projectile_u_i.html", "class_incoming_projectile_u_i" ],
    [ "LerpResetCameraRotation", "class_lerp_reset_camera_rotation.html", "class_lerp_reset_camera_rotation" ],
    [ "LinkedSet", "class_linked_set.html", "class_linked_set" ],
    [ "MainMenu", "class_main_menu.html", "class_main_menu" ],
    [ "NewEditModeTest", "class_new_edit_mode_test.html", "class_new_edit_mode_test" ],
    [ "Outline", "class_outline.html", "class_outline" ],
    [ "OutlineEffect", "class_outline_effect.html", "class_outline_effect" ],
    [ "ParachuteFallBehavior", "class_parachute_fall_behavior.html", "class_parachute_fall_behavior" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "PlayerDebugInfo", "class_player_debug_info.html", "class_player_debug_info" ],
    [ "ProjectileBehavior", "class_projectile_behavior.html", "class_projectile_behavior" ],
    [ "PropellerSpinner", "class_propeller_spinner.html", "class_propeller_spinner" ],
    [ "ScoreManager", "class_score_manager.html", "class_score_manager" ],
    [ "ScoreTextUpdater", "class_score_text_updater.html", "class_score_text_updater" ],
    [ "SetRenderQueue", "class_set_render_queue.html", "class_set_render_queue" ],
    [ "SetupSpawner", "class_setup_spawner.html", "class_setup_spawner" ],
    [ "SoundManager", "class_sound_manager.html", "class_sound_manager" ],
    [ "StrapBehavior", "class_strap_behavior.html", "class_strap_behavior" ],
    [ "TerrainBehavior", "class_terrain_behavior.html", "class_terrain_behavior" ],
    [ "TerrainSampler", "class_terrain_sampler.html", "class_terrain_sampler" ],
    [ "WeatherMode", "class_weather_mode.html", "class_weather_mode" ]
];